apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "test-ehr-service-backend-config"}'
  labels:
    application: test-ehr
  name: test-ehr-service
spec:
  type: ClusterIP
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    application: test-ehr
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: test-ehr-service-backend-config
spec:
  healthCheck:
    type: HTTP
    requestPath: /test-ehr/r4/Patient
    port: 8080
